### ISSUE TITLE
permission to use

### ISSUE THREAD

**Issue by PercivalCrump** [falltergeist/int2ssl#5]
Доброго дня, спасибо за прекрасную доработку декомпилера для sFall! Хочу использовать его внутри своего, не менее прекрасного, редактора сохранений:
[https://www.nexusmods.com/fallout2/mods/52]

Благословите!
PercivalCrump@outlook.com

**Comment by alexeevdv** [comment]
Hi! It is distributed under the GPL v3 license. You can find answers for all your questions [here](https://www.gnu.org/licenses/gpl-faq.en.html#using-programs). I hope it helps. Good luck with your project!
